### ISSUE TITLE
Errors on TYPO3 12.4.21  & PHP 8.2

### ISSUE THREAD

**Issue by bh-teufels** [joachimruhs/myttaddressmap#27]
Using myttaddressmap on a local TYPO3 12.4.21 & PHP 8.2 i get following errors:

plugin preview (myttaddressmap_map) in Backend show  "ERROR: Line 1: Invalid document end"
Error log on page with plugin shows 

Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1476107295: PHP Runtime Deprecation Notice: Creation of dynamic property WSR\Myttaddressmap\Controller\AjaxController::$configuration is deprecated in /app/vendor/wsr/myttaddressmap/Classes/Controller/AjaxController.php line 212 | TYPO3\CMS\Core\Error\Exception thrown in file /app/vendor/typo3/cms-core/Classes/Error/ErrorHandler.php in line 141. Requested URL: https://development.localhost/index.php?id=165

**Comment by joachimruhs** [comment]
Hi,
which version of myttaddressmap?

**Comment by bh-teufels** [comment]
i am using the latest version 2.2.6

**Comment by joachimruhs** [comment]
Hi,
with composer?

**Comment by joachimruhs** [comment]
I have just made a release 2.2.9.

**Comment by bh-teufels** [comment]
yes with composer 
i make a clearcache and do a update

**Comment by bh-teufels** [comment]
same errors on 2.2.9

**Comment by joachimruhs** [comment]
I can't reproduce it. It works fine without errors in the log here https://comp.joachim-ruhs.de/maps/myttaddressmap

**Comment by bh-teufels** [comment]
any ideas what could be causing this?

**Comment by joachimruhs** [comment]
Hi,
have you installed the Ext on an other server?
Did it run there without errors?

**Comment by bh-teufels** [comment]
tested it right now on other TYPO3 Installation on other server
TYPO3 12.4.22
PHP 8.3.12
myttaddressmap 2.2.9

BE Preview same error
FE same problem: Pins not showing
Log Errors:
```
Core: Exception handler (WEB): Uncaught TYPO3 Exception: TYPO3\CMS\Core\Localization\LanguageServiceFactory::create(): Argument #1 ($locale) must be of type TYPO3\CMS\Core\Localization\Locale|string, null given, called in vendor/wsr/myttaddressmap/Classes/Controller/AjaxController.php on line 281 | TypeError thrown in file vendor/typo3/cms-core/Classes/Localization/LanguageServiceFactory.php in line 45. Requested URL: https://test.de/index.php?id=206

Core: Error handler (FE): PHP Warning: Undefined array key "typo3Language" in vendor/wsr/myttaddressmap/Classes/Controller/AjaxController.php line 280
```

**Comment by bh-teufels** [comment]
if i manually fix the PHP Runtime Deprecation Error on my local development installation i get the same errors

**Comment by joachimruhs** [comment]
Have you set up the language?

**Comment by bh-teufels** [comment]
yes in the site configuration 

```
languages:
  -
    title: English
    enabled: true
    locale: en_US.UTF-8
    hreflang: en
    base: /
    websiteTitle: ''
    navigationTitle: EN
    flag: en-us-gb
    languageId: 0
    deeplTargetLanguage: EN-US
  -
    title: German
    enabled: true
    locale: de_DE
    hreflang: ''
    base: /de/
    xml_sitemap_path: ''
    websiteTitle: ''
    navigationTitle: DE
    fallbackType: strict
    fallbacks: ''
    flag: de
    languageId: 1
    deeplTargetLanguage: DE
  -
    title: 'Chinese (Simplified)'
    enabled: true
    locale: zh_CN
    hreflang: ''
    base: /cn/
    xml_sitemap_path: ''
    websiteTitle: ''
    navigationTitle: 汉语
    fallbackType: strict
    fallbacks: ''
    flag: cn
    languageId: 2
    deeplTargetLanguage: ZH
```
